### ISSUE TITLE
Ne fonctionne pas sur un projet node de base

### ISSUE THREAD

**Issue by wildmatthieu** [WildCodeSchool-CDA-LYON-02-2024/wcs-chart-lib#54]
Ce n'est pas spécifié dans la documentation ; il semble qu'il faille utiliser une lib/framework web pour utiliser ce package ? (react, ...)

**Comment by brrrrrbrrrr** [comment]
Oui c'est une librairie qui utilise react, on va le rajouter dans la documentation, merci de ton retour
