### ISSUE TITLE
Responsive does not work with the first example

### ISSUE THREAD

**Issue by wildmatthieu** [WildCodeSchool-CDA-LYON-02-2024/wcs-chart-lib#55]
Le responsive ne marche pas avec le premier exemple donné dans le README

![image](https://github.com/WildCodeSchool-CDA-LYON-02-2024/wcs-chart-lib/assets/144900231/aee4e8c9-6569-48f2-bb9f-2aa49ad58086)

**Comment by wildmatthieu** [comment]
![image](https://github.com/WildCodeSchool-CDA-LYON-02-2024/wcs-chart-lib/assets/144900231/1a0f1230-d5ee-4238-8a5d-69bdf40f96e7)

**Comment by techmefr** [comment]
en spécifiant la taille si c'est le cas c'est cette issue ?
https://github.com/WildCodeSchool-CDA-LYON-02-2024/wcs-chart-lib/issues/25

**Comment by brrrrrbrrrr** [comment]
Cette [issue](https://github.com/WildCodeSchool-CDA-LYON-02-2024/wcs-chart-lib/issues/25) renvoi a ce problème.
Quand on spécifie des pixels, le graphique garde les memes dimensions et n'est pas responsive.

Si tu ne specifie pas de largeur et de hauteur, le graphique prend la largeur du navigataur, et la moitié de la hauteur du navigateur, et est responsive

**Comment by techmefr** [comment]
on a mit à jour la doc pour préciser de façon plus clair que si une tailel est définie alors le responsive ne s'applique plus pour correspondre à la taille
