### ISSUE TITLE
Chevauchement de valeurs sur l'axe X

### ISSUE THREAD

**Issue by sdp971** [WildCodeSchool-CDA-LYON-02-2024/wcs-chart-lib#57]
![Capture d'écran 2024-04-30 110041](https://github.com/WildCodeSchool-CDA-LYON-02-2024/wcs-chart-lib/assets/76818441/3a263a16-eab6-49c4-bb7c-e3828fa37d1c)
Voici le rendu que j'ai en utilisant ce code :
 ``
import { WCS } from 'wcs-chart-lib';
import './App.css'

function App() {
  
 const config = {
   type: 'line',
   height: 1000,
   width: 1000,
 };
  
  const dataset = [
    {
      tag: ['Titre1'],
      data: {
        labels: [
          'Janvier',
          'Février',
          'Mars',
          'Avril',
          'Mai',
          'Juin',
          'Juillet',
          'Août',
          'Septembre',
          'Octobre',
          'Novembre',
          'Décembre',
        ],
        values: [[88, 100, 30, 40, 50, 60, 51, 11, 51, 23, 47, 56]],
      },
    },
  ];
``
  return (
    <div>
      <WCS config={config} dataset={dataset} theme='sea' />
    </div>
  );
}

export default App

**Comment by brrrrrbrrrr** [comment]
It's fixed, it will be visible in the next npm version
