### ISSUE TITLE
Example for the point chart

### ISSUE THREAD

**Issue by JohLav** [WildCodeSchool-CDA-LYON-02-2024/wcs-chart-lib#60]
The following example works correctly:
```js
const config = {
  type: 'point',
  toLine: false,
  grid: true,
  radius: 5,
};
```
However, there is a point on the ordinate axis which is not usually found on a graph like this.
<img width="963" alt="Capture d’écran 2024-04-30 à 11 08 41" src="https://github.com/WildCodeSchool-CDA-LYON-02-2024/wcs-chart-lib/assets/115481046/e3ed9f6b-1e79-4450-8996-6c2898d0a9e7">

**Comment by brrrrrbrrrr** [comment]
Thank you for your suggestions, this is how the graphics are displayed, but this may be an option added later if it bothers users

Example for the chartJs library : 
![scatter](https://github.com/WildCodeSchool-CDA-LYON-02-2024/wcs-chart-lib/assets/114990937/70ce89c4-194c-4447-b52d-c292e11c90b5)

![exempleScatter](https://github.com/WildCodeSchool-CDA-LYON-02-2024/wcs-chart-lib/assets/114990937/6079ccd9-3610-4007-aa5f-aabaaced4416)
