### ISSUE TITLE
Choix des couleurs de theme Sea et Nature

### ISSUE THREAD

**Issue by sdp971** [WildCodeSchool-CDA-LYON-02-2024/wcs-chart-lib#62]
Les couleurs choisies peuvent causer une mauvaise expérience utilisateur (inconfort visuel). Peut-être opter pour d'autres couleurs.

**Comment by techmefr** [comment]
cela arrivera avec le snouveaux thèmes et la personnalisation de ceux-ci (voir l'issue https://github.com/WildCodeSchool-CDA-LYON-02-2024/wcs-chart-lib/issues/14 )
