### ISSUE TITLE
Exemple d'implémentation

### ISSUE THREAD

**Issue by sdp971** [WildCodeSchool-CDA-LYON-02-2024/wcs-chart-lib#63]
J'ai recopié l'exemple d'implémentation en faisant un copier coller sans me poser de questions mais ça n'a pas marché. IL fallait rajouter le config et le dataset. Ce serait bien je pense de le donner de base en même temps que l'exemple d'implémentation.

**Comment by techmefr** [comment]
il est au début de la doc, chaque élément est donné et expliqué l'un après l'autre pour savoir à quoi il sert et comment s'en servir

**Comment by sdp971** [comment]
La documentation dit au début les props qu'il faut passer mais ce serait mieux d'avoir un exemple de props avec l'exemple d'implémentation. C'était une suggestion d'amélioration pour améliorer l'expérience utilisateur.

**Comment by techmefr** [comment]
Merci pour le conseil pertinent
